// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package models

const TableNameAuthor = "author"

// Author mapped from table <author>
type Author struct {
	ID   int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name string `gorm:"column:name" json:"name"`
	Article Article
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
